# Site settings
title: SanFranciscoStoryTelling
author: Andreu Guitart
description: This is a story of the recorded crime data from the city during 2003-2015.

# Build settings
theme: minima
plugins:
  - jekyll-feed
